<a href="https://colab.research.google.com/github/Shionfer0M/LINEAR-PROGRAMMING/blob/master/Programaci%C3%B3n_Lineal_Chido.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pulp

     |████████████████████████████████| 40.6MB 100kB/s 


In [2]:
!pip install numpy

In [213]:
import numpy as np
from pulp import *
#Pidiendo datos para realizar el método
num_estadosf = int(input("Proporciona el número de estados::"))
num_decisionesf = int(input("Proporciona el número de decisiones::"))
edosf = []
desisf = []

#listando estados | decision | vector de probabilidad

vect_auxf = []
matriz_prob_por_decisf= np.zeros((1,num_estadosf))
print("Digita el estado, decision y vector de probabilidad correspondiente.")
optionf = 1
iteracionf = 0


while optionf  >=1 :

  if iteracionf < 1: #Aqui lo utilizo para llenar mientras la matriz solo tiene un solo registro, es decir, 
  #solo hay un renglón correspondiente a un estado con una desición y este guarda dicho vector de probabilidad.
    auxf = int(input("Estado.. "))#pide estado
    edosf.append(auxf)

    aux1f = int(input("Desición tomada.. "))#pide la decision del estado tomado anteriormente 
    desisf.append(aux1f)

    print("vector de probabilidad del estado %d tomada la decisión %d"%(edosf[iteracionf],desisf[iteracionf])) # Pide el vector correspondiente al estado y decision anteriormente solicitado 
    for i in range(0,num_estadosf):
      auxif = float(input(" "))
      matriz_prob_por_decisf[0,i] = auxif

  else:
    auxf = int(input("Estado.. "))
    edosf.append(auxf)
    aux1f = int(input("Desición tomada.. "))
    desisf.append(aux1f)
    print("vector de probabilidad del estado %d tomada la decisión %d"%(edosf[iteracionf],desisf[iteracionf]))
    for i in range(num_estadosf):
      aux3f = float(input(" "))
      vect_auxf.append(aux3f)

    matriz_prob_por_decisf = np.vstack([matriz_prob_por_decisf, vect_auxf])
    vect_auxf.clear()

  optionf = int(input("Dar otra asignación?? SI= 1 | NO = 0"))
  iteracionf +=1

Proporciona el número de estados::3
Proporciona el número de decisiones::3
Digita el estado, decision y vector de probabilidad correspondiente.
Estado.. 0
Desición tomada.. 1
vector de probabilidad del estado 0 tomada la decisión 1
 0.4
 0.5
 0.1
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 0
Desición tomada.. 2
vector de probabilidad del estado 0 tomada la decisión 2
 0.7
 0.2
 0.1
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 0
Desición tomada.. 3
vector de probabilidad del estado 0 tomada la decisión 3
 0.2
 0.5
 0.3
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 1
Desición tomada.. 1
vector de probabilidad del estado 1 tomada la decisión 1
 0.1
 0.7
 0.2
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 1
Desición tomada.. 2
vector de probabilidad del estado 1 tomada la decisión 2
 0.3
 0.6
 0.1
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 1
Desición tomada.. 3
vector de probabilidad del estado 1 tomada la decisión 3
 0
 0.7
 0.3
Dar otra asignación?? SI= 1 | NO = 01
Estado.. 2
D

In [229]:
costosf = []
for f in range(0,iteracionf):
  aux_costosf = float(input("Costo de EDO %d  --> DEC %d ... "%(edosf[f],desisf[f])))
  costosf.append(aux_costosf)

Costo de EDO 0  --> DEC 1 ... 280
Costo de EDO 0  --> DEC 2 ... 220
Costo de EDO 0  --> DEC 3 ... 258
Costo de EDO 1  --> DEC 1 ... 250
Costo de EDO 1  --> DEC 2 ... 110
Costo de EDO 1  --> DEC 3 ... 255
Costo de EDO 2  --> DEC 1 ... 220
Costo de EDO 2  --> DEC 2 ... -130
Costo de EDO 2  --> DEC 3 ... 300


In [230]:
costosf

[280.0, 220.0, 258.0, 250.0, 110.0, 255.0, 220.0, -130.0, 300.0]

In [231]:
matriz_prob_por_decisf

array([[0.4, 0.5, 0.1],
       [0.7, 0.2, 0.1],
       [0.2, 0.5, 0.3],
       [0.1, 0.7, 0.2],
       [0.3, 0.6, 0.1],
       [0. , 0.7, 0.3],
       [0.1, 0.2, 0.7],
       [0.1, 0.7, 0.2],
       [0. , 0.2, 0.8]])

In [232]:
#IMPRIMIENDO COMPILACION DE DATOS DE ESTADOS | DECISION TOMADA | VECTOR DE PROB ASOCIOADO
for i in range(0,len(edosf)):
  print("ESTADO %d   -> DECISION %d   | vector de probabilidad "%(edosf[i],desisf[i]),matriz_prob_por_decisf[i,:])

ESTADO 0   -> DECISION 1   | vector de probabilidad  [0.4 0.5 0.1]
ESTADO 0   -> DECISION 2   | vector de probabilidad  [0.7 0.2 0.1]
ESTADO 0   -> DECISION 3   | vector de probabilidad  [0.2 0.5 0.3]
ESTADO 1   -> DECISION 1   | vector de probabilidad  [0.1 0.7 0.2]
ESTADO 1   -> DECISION 2   | vector de probabilidad  [0.3 0.6 0.1]
ESTADO 1   -> DECISION 3   | vector de probabilidad  [0.  0.7 0.3]
ESTADO 2   -> DECISION 1   | vector de probabilidad  [0.1 0.2 0.7]
ESTADO 2   -> DECISION 2   | vector de probabilidad  [0.1 0.7 0.2]
ESTADO 2   -> DECISION 3   | vector de probabilidad  [0.  0.2 0.8]


In [233]:
#ESTA PARTE YA CAMBIA A YIK LO CHIDO
costos2 = costosf.copy()
costosyi=[]
for g in range(len(costos2)):
  costos2[g] = (f"y_{edosf[g]}{desisf[g]}")
  costosyi.append(costos2[g])
    #if costos2[g] >= 0:
print(costosyi)
#print(costosf)

['y_01', 'y_02', 'y_03', 'y_11', 'y_12', 'y_13', 'y_21', 'y_22', 'y_23']


In [234]:
#costos_int_str=costosf.copy()
print(costosf)
nuevafo=[] #aquí se v a guardar la variabes y*costo como una cadena
for pr in range(len(costos2)): #<------------------------------------------------------------- ESTO SE CAMBIA
  paimpr=(f"{costosf[pr]}*{costosyi[pr]}") #hace lo mismo y*costo como
  nuevafo.append(paimpr) #lo guarda en cadena
sep = '+'
#resta = '-'
fobj = sep.join(nuevafo)
print("LA FUNCIÓN OBJETIVO PARA EL PROBLEMA DE PROGRAMACIÓN LINEAL ES: ")
print(fobj)

[280.0, 220.0, 258.0, 250.0, 110.0, 255.0, 220.0, -130.0, 300.0]
LA FUNCIÓN OBJETIVO PARA EL PROBLEMA DE PROGRAMACIÓN LINEAL ES: 
280.0*y_01+220.0*y_02+258.0*y_03+250.0*y_11+110.0*y_12+255.0*y_13+220.0*y_21+-130.0*y_22+300.0*y_23


In [235]:
sep='+'
#print(costosyi) # ESTA PRIMER RESTRICCIÓN NO CAMBIA DEPENDE DE LAS VARIABLES DE LOS COSTOS
print("PRIMERA RESTRICCIÓN:")
prestriccion = sep.join(costosyi)
primeraresctriccion = (f"{prestriccion}==1")
print(primeraresctriccion)

PRIMERA RESTRICCIÓN:
y_01+y_02+y_03+y_11+y_12+y_13+y_21+y_22+y_23==1


In [238]:
#ESTO DEBE DE ESTAR SIEMPRE AL ULTIMO ES COMO LA ULTIMA RESTRICCIÓN DONDE LAS YIK SON >= 0 PERO NO SE PONEN EN EL PROBLEMA PARA RESOLVER SOLO PARA VISUALIZACIÓN
print("LAS VARIABLES DEBEN SER: ")
sepc = ','
ur = sepc.join(costosyi)
urv = (f"{ur} >= 0")
print(urv)
#GENERANDO LAS DEMAS RESTRICCIÓNES SABIENDO QUE ES N-1 (N ES ESTADOS)
primeraparteyi = dict()
segundaparteyi = dict() 
laresjunta = dict()
sumrjunta = dict()
pl_lista = dict()
print("LAS SIGUIENTES RESTRICCIONES CORRESPONEN A SU RESPECTIVO ESTADO - 1")
for p in range(0,num_estadosf-1):
  primeraparteyi['su'+str(p)]= []
  segundaparteyi['supsp'+str(p)]= []
  #laresjunta['laresumando'+str(p)]
  #sumrjunta['sumrsumando'+str(p)]
  #pl_lista['plsumando'+str(p)]
  for rta in range(len(costos2)): #restriva2
    if edosf[rta] == p:
      reccs = (f"y{edosf[rta]}{desisf[rta]}") #acomodar restriccions2 --> rccss
      primeraparteyi['su'+str(p)].append(reccs) 
  #print(primeraparteyi['su'+str(p)]) #funciona
#print(primeraparteyi['su1']) 
  for rtasg in range(len(costosf)): #restrivaseg2
    #for rtasgres in range(0,num_estadosf-1): #rest2
      #if edosf[rtasgres] == p:
      rccssp2=(f"{matriz_prob_por_decisf[rtasg,p]}*{costosyi[rtasg]}")  #sp2 ----> rccssp2
      segundaparteyi['supsp'+str(p)].append(rccssp2) #segundaparte2 ----> supsp(p)
  #print(segundaparteyi['supsp'+str(p)]) #funciona
  #print(su(p))
  #print(supsp(p))
  laresjunta['laresumando'+str(p)] = sep.join(primeraparteyi['su'+str(p)]) #cambiar larespr2------->lrps 
  sumrjunta['sumrsumando'+str(p)] = sep.join(segundaparteyi['supsp'+str(p)]) #cambiar 
  pl_lista['plsumando'+str(p)]=(f"{laresjunta['laresumando'+str(p)]}-({sumrjunta['sumrsumando'+str(p)]})==0")
  #print("VAMOS A VER LAS NUEVAS RESTRICCIONES")
  print(pl_lista['plsumando'+str(p)])

print(matriz_prob_por_decisf)

LAS VARIABLES DEBEN SER: 
y_01,y_02,y_03,y_11,y_12,y_13,y_21,y_22,y_23 >= 0
LAS SIGUIENTES RESTRICCIONES CORRESPONEN A SU RESPECTIVO ESTADO - 1
y01+y02+y03-(0.4*y_01+0.7*y_02+0.2*y_03+0.1*y_11+0.3*y_12+0.0*y_13+0.1*y_21+0.1*y_22+0.0*y_23)==0
y11+y12+y13-(0.5*y_01+0.2*y_02+0.5*y_03+0.7*y_11+0.6*y_12+0.7*y_13+0.2*y_21+0.7*y_22+0.2*y_23)==0
[[0.4 0.5 0.1]
 [0.7 0.2 0.1]
 [0.2 0.5 0.3]
 [0.1 0.7 0.2]
 [0.3 0.6 0.1]
 [0.  0.7 0.3]
 [0.1 0.2 0.7]
 [0.1 0.7 0.2]
 [0.  0.2 0.8]]


In [239]:
#ESTO DEBE DE ESTAR SIEMPRE AL ULTIMO ES COMO LA ULTIMA RESTRICCIÓN DONDE LAS YIK SON >= 0 PERO NO SE PONEN EN EL PROBLEMA PARA RESOLVER SOLO PARA VISUALIZACIÓN
print("LAS VARIABLES DEBEN SER: ")
sepc = ','
ur = sepc.join(costosyi)
urv = (f"{ur} >= 0")
print(urv)

LAS VARIABLES DEBEN SER: 
y_01,y_02,y_03,y_11,y_12,y_13,y_21,y_22,y_23 >= 0


In [240]:
#RECORDANDO EL PROBLEMA PARA PROGRAMACIÓN LINEAL
print("RECORDANDO EL PROBLEMA")
print("FUNCIÓN OBJETIVO: ")
print(fobj) 
print("SUJETO A: ")
print(primeraresctriccion)
for p in range(0,num_estadosf-1):
  print(pl_lista['plsumando'+str(p)])
print(urv)

RECORDANDO EL PROBLEMA
FUNCIÓN OBJETIVO: 
280.0*y_01+220.0*y_02+258.0*y_03+250.0*y_11+110.0*y_12+255.0*y_13+220.0*y_21+-130.0*y_22+300.0*y_23
SUJETO A: 
y_01+y_02+y_03+y_11+y_12+y_13+y_21+y_22+y_23==1
y01+y02+y03-(0.4*y_01+0.7*y_02+0.2*y_03+0.1*y_11+0.3*y_12+0.0*y_13+0.1*y_21+0.1*y_22+0.0*y_23)==0
y11+y12+y13-(0.5*y_01+0.2*y_02+0.5*y_03+0.7*y_11+0.6*y_12+0.7*y_13+0.2*y_21+0.7*y_22+0.2*y_23)==0
y_01,y_02,y_03,y_11,y_12,y_13,y_21,y_22,y_23 >= 0


In [241]:
#GENERANDO EL MODELO Y RESOLVIENDO
plineal= LpProblem("PROGRAMACIÓN_LINEAL", LpMinimize)
variablesyi = [str(edosf[i])+str(desisf[i]) for i in range(0,iteracionf)] #definiendo variables

variablesenteras = LpVariable.matrix("y", variablesyi, lowBound= 0 ) #otra vez trabajando cada variable, esta parte es importante para hacer operación
operacionvariables = np.array(variablesenteras)

funcionobjetivo = lpSum(operacionvariables*costosf) #suma los costos con las variables para la fnción objetivo

plineal +=  funcionobjetivo #operación con función objetivo

plineal += lpSum(operacionvariables) == 1 #trae la primera restricción
#Para las demas restricciones N-1 donde N son los estados
for p in range(0,num_estadosf-1):
  primeraparteyi['su'+str(p)]= []
  segundaparteyi['supsp'+str(p)]= []
  for rta in range(len(costos2)): #<----------------------------------------------------------- CAMBIA 
    if edosf[rta] == p:
      reccs = (operacionvariables[rta])
      primeraparteyi['su'+str(p)].append(reccs) #para la primera parte de las yik
  for rtasg in range(len(costos2)): #<------------------------------------------------------------- CAMBIA
      rccssp2=(matriz_prob_por_decisf[rtasg,p]*operacionvariables[rtasg])  
      segundaparteyi['supsp'+str(p)].append(rccssp2) #segunda parte para las yik
  plineal += (((lpSum(primeraparteyi['su'+str(p)])))-((lpSum((segundaparteyi['supsp'+str(p)]))))) == 0
plineal

print(plineal) #imprime el modelado y ya resolviendo la parte de las restricciones de la primera y segunda parte
#resolviendo
plineal.solve(PULP_CBC_CMD())
status =  LpStatus[plineal.status]
print(status)

#imprimiendo resultados
print("EL COSTO ES:", plineal.objective.value())
# Decision Variables
print("EL VALOR PARA CADA VARIABLE ES:")
for va in plineal.variables():
    try:
        print(va.name,"=", va.value())
    except:
        print(" ")

PROGRAMACIÓN_LINEAL:
MINIMIZE
280.0*y_01 + 220.0*y_02 + 258.0*y_03 + 250.0*y_11 + 110.0*y_12 + 255.0*y_13 + 220.0*y_21 + -130.0*y_22 + 300.0*y_23 + 0.0
SUBJECT TO
_C1: y_01 + y_02 + y_03 + y_11 + y_12 + y_13 + y_21 + y_22 + y_23 = 1

_C2: 0.6 y_01 + 0.3 y_02 + 0.8 y_03 - 0.1 y_11 - 0.3 y_12 - 0.1 y_21
 - 0.1 y_22 = 0

_C3: - 0.5 y_01 - 0.2 y_02 - 0.5 y_03 + 0.3 y_11 + 0.4 y_12 + 0.3 y_13
 - 0.2 y_21 - 0.7 y_22 - 0.2 y_23 = 0

VARIABLES
y_01 Continuous
y_02 Continuous
y_03 Continuous
y_11 Continuous
y_12 Continuous
y_13 Continuous
y_21 Continuous
y_22 Continuous
y_23 Continuous

Optimal
EL COSTO ES: 106.31068099999999
EL VALOR PARA CADA VARIABLE ES:
y_01 = 0.0
y_02 = 0.0
y_03 = 0.24271845
y_11 = 0.0
y_12 = 0.59223301
y_13 = 0.0
y_21 = 0.0
y_22 = 0.16504854
y_23 = 0.0


In [242]:
#EN LO ANTERIOR YA SE VE QUE POLÍTICA TOMAR DONDE HAY VALOR != 0 ES LA DECICIÓN A TOMAR y_ik k---> es la decisión a tomar 
#Ejemplo: Tiene valor la y_01, y_11,y_22,y_33 entonces la política es (1,1,2,3)
#seppoliticas= '\n'
yipol=[] 
for vp in plineal.variables():
    try:
      if(vp.value()!=0):
        yiop = (vp.name)
        yipol.append(yiop) #se guarda las variables de solución que nos interesa en una lista
    except:
        print(" ")
#print(yipol)

cadenapolitica = "".join(yipol) #Convierte la lista en cadena
#print(cadenapolitica)

#rangocadena=len(cadenapolitica) #Posiblemente se ocupe es el tamaño de la cadena
#print(rangocadena)

print("ENTONCES LA POLÍTICA OPTIMA ES: ")
politicaoptimapl=[]
contador1=3 #El contador empieza desde la posición 3 donde esta la primera K osea la primer decisión
for vd11 in range(len(yipol)):
  psalida = cadenapolitica[contador1]
  politicaoptimapl.append(psalida)
  #print(psalida)
  contador1 = contador1+4
print(politicaoptimapl)

ENTONCES LA POLÍTICA OPTIMA ES: 
['3', '2', '2']


In [247]:
#MENÚ SI QUIERE MAXIMIZAR O MINIMIZAR
print("POR FAVOR SELECCIONE UNA OPTCIÓN")
print("1 .- MINIMIZAR")
print("2 .- MAXIMIZAR")
opcionpl=int(input("LA OPCIÓN...: "))
if opcionpl is 1:
  
  plineal= LpProblem("PROGRAMACIÓN_LINEAL", LpMinimize)
  variablesyi = [str(edosf[i])+str(desisf[i]) for i in range(0,iteracionf)] #definiendo variables

  variablesenteras = LpVariable.matrix("y", variablesyi, lowBound= 0 ) #otra vez trabajando cada variable, esta parte es importante para hacer operación
  operacionvariables = np.array(variablesenteras)

  funcionobjetivo = lpSum(operacionvariables*costosf) #suma los costos con las variables para la fnción objetivo

  plineal +=  funcionobjetivo #operación con función objetivo

  plineal += lpSum(operacionvariables) == 1 #trae la primera restricción
  #Para las demas restricciones N-1 donde N son los estados
  for p in range(0,num_estadosf-1):
    primeraparteyi['su'+str(p)]= []
    segundaparteyi['supsp'+str(p)]= []
    for rta in range(len(costos2)): 
      if edosf[rta] == p:
        reccs = (operacionvariables[rta])
        primeraparteyi['su'+str(p)].append(reccs) #para la primera parte de las yik
    for rtasg in range(len(costos2)): 
        rccssp2=(matriz_prob_por_decisf[rtasg,p]*operacionvariables[rtasg])  
        segundaparteyi['supsp'+str(p)].append(rccssp2) #segunda parte para las yik
    plineal += (((lpSum(primeraparteyi['su'+str(p)])))-((lpSum((segundaparteyi['supsp'+str(p)]))))) == 0
  plineal

  print(plineal) #imprime el modelado y ya resolviendo la parte de las restricciones de la primera y segunda parte
  #resolviendo
  plineal.solve(PULP_CBC_CMD())
  status =  LpStatus[plineal.status]
  print(status)

  #imprimiendo resultados
  print("EL COSTO ES:", plineal.objective.value())
  # Decision Variables
  print("EL VALOR PARA CADA VARIABLE ES:")
  for va in plineal.variables():
     try:
          print(va.name,"=", va.value())
     except:
          print(" ")
  #EN LO ANTERIOR YA SE VE QUE POLÍTICA TOMAR DONDE HAY VALOR != 0 ES LA DECICIÓN A TOMAR y_ik k---> es la decisión a tomar 
  #Ejemplo: Tiene valor la y_01, y_11,y_22,y_33 entonces la política es (1,1,2,3)
  #seppoliticas= '\n'
  yipol=[] 
  for vp in plineal.variables():
      try:
        if(vp.value()!=0):
          yiop = (vp.name)
          yipol.append(yiop) #se guarda las variables de solución que nos interesa en una lista
      except:
          print(" ")
  #print(yipol)

  cadenapolitica = "".join(yipol) #Convierte la lista en cadena
  #print(cadenapolitica)

  #rangocadena=len(cadenapolitica) #Posiblemente se ocupe es el tamaño de la cadena
  #print(rangocadena)

  print("ENTONCES LA POLÍTICA OPTIMA ES: ")
  politicaoptimapl=[]
  contador1=3 #El contador empieza desde la posición 3 donde esta la primera K osea la primer decisión
  for vd11 in range(len(yipol)):
   psalida = cadenapolitica[contador1]
   politicaoptimapl.append(psalida)
   #print(psalida)
   contador1 = contador1+4
  print(politicaoptimapl)

elif opcionpl is 2:
  plineal= LpProblem("PROGRAMACIÓN_LINEAL", LpMaximize)
  variablesyi = [str(edosf[i])+str(desisf[i]) for i in range(0,iteracionf)] #definiendo variables

  variablesenteras = LpVariable.matrix("y", variablesyi, lowBound= 0 ) #otra vez trabajando cada variable, esta parte es importante para hacer operación
  operacionvariables = np.array(variablesenteras)

  funcionobjetivo = lpSum(operacionvariables*costosf) #suma los costos con las variables para la fnción objetivo

  plineal +=  funcionobjetivo #operación con función objetivo

  plineal += lpSum(operacionvariables) == 1 #trae la primera restricción
  #Para las demas restricciones N-1 donde N son los estados
  for p in range(0,num_estadosf-1):
    primeraparteyi['su'+str(p)]= []
    segundaparteyi['supsp'+str(p)]= []
    for rta in range(len(costos2)): 
      if edosf[rta] == p:
        reccs = (operacionvariables[rta])
        primeraparteyi['su'+str(p)].append(reccs) #para la primera parte de las yik
    for rtasg in range(len(costos2)): 
        rccssp2=(matriz_prob_por_decisf[rtasg,p]*operacionvariables[rtasg])  
        segundaparteyi['supsp'+str(p)].append(rccssp2) #segunda parte para las yik
    plineal += (((lpSum(primeraparteyi['su'+str(p)])))-((lpSum((segundaparteyi['supsp'+str(p)]))))) == 0
  plineal

  print(plineal) #imprime el modelado y ya resolviendo la parte de las restricciones de la primera y segunda parte
  #resolviendo
  plineal.solve(PULP_CBC_CMD())
  status =  LpStatus[plineal.status]
  print(status)

  #imprimiendo resultados
  print("EL COSTO ES:", plineal.objective.value())
  # Decision Variables
  print("EL VALOR PARA CADA VARIABLE ES:")
  for va in plineal.variables():
     try:
          print(va.name,"=", va.value())
     except:
          print(" ")
  #EN LO ANTERIOR YA SE VE QUE POLÍTICA TOMAR DONDE HAY VALOR != 0 ES LA DECICIÓN A TOMAR y_ik k---> es la decisión a tomar 
  #Ejemplo: Tiene valor la y_01, y_11,y_22,y_33 entonces la política es (1,1,2,3)
  #seppoliticas= '\n'
  yipol=[] 
  for vp in plineal.variables():
      try:
        if(vp.value()!=0):
          yiop = (vp.name)
          yipol.append(yiop) #se guarda las variables de solución que nos interesa en una lista
      except:
          print(" ")
  #print(yipol)

  cadenapolitica = "".join(yipol) #Convierte la lista en cadena
  #print(cadenapolitica)

  #rangocadena=len(cadenapolitica) #Posiblemente se ocupe es el tamaño de la cadena
  #print(rangocadena)

  print("ENTONCES LA POLÍTICA OPTIMA ES: ")
  politicaoptimapl=[]
  contador1=3 #El contador empieza desde la posición 3 donde esta la primera K osea la primer decisión
  for vd11 in range(len(yipol)):
   psalida = cadenapolitica[contador1]
   politicaoptimapl.append(psalida)
   #print(psalida)
   contador1 = contador1+4
  print(politicaoptimapl)

else:
  print("NO ESTA EN LAS OPCIONES")

POR FAVOR SELECCIONE UNA OPTCIÓN
1 .- MINIMIZAR
2 .- MAXIMIZAR
LA OPCIÓN...: 2
PROGRAMACIÓN_LINEAL:
MAXIMIZE
280.0*y_01 + 220.0*y_02 + 258.0*y_03 + 250.0*y_11 + 110.0*y_12 + 255.0*y_13 + 220.0*y_21 + -130.0*y_22 + 300.0*y_23 + 0.0
SUBJECT TO
_C1: y_01 + y_02 + y_03 + y_11 + y_12 + y_13 + y_21 + y_22 + y_23 = 1

_C2: 0.6 y_01 + 0.3 y_02 + 0.8 y_03 - 0.1 y_11 - 0.3 y_12 - 0.1 y_21
 - 0.1 y_22 = 0

_C3: - 0.5 y_01 - 0.2 y_02 - 0.5 y_03 + 0.3 y_11 + 0.4 y_12 + 0.3 y_13
 - 0.2 y_21 - 0.7 y_22 - 0.2 y_23 = 0

VARIABLES
y_01 Continuous
y_02 Continuous
y_03 Continuous
y_11 Continuous
y_12 Continuous
y_13 Continuous
y_21 Continuous
y_22 Continuous
y_23 Continuous

Optimal
EL COSTO ES: 282.00000000021333
EL VALOR PARA CADA VARIABLE ES:
y_01 = 0.0
y_02 = 0.0
y_03 = 0.0
y_11 = 1e-12
y_12 = -3.3333333e-13
y_13 = 0.4
y_21 = 0.0
y_22 = 0.0
y_23 = 0.6
ENTONCES LA POLÍTICA OPTIMA ES: 
['1', '2', '3', '3']
